<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protobuf.AuthResponse</code>
 */
class AuthResponse extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Account::initOnce();
        parent::__construct();
    }

}

