<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: code.proto

namespace Protobuf;

/**
 * 业务status code
 *
 * Protobuf enum <code>Protobuf\Code</code>
 */
class Code
{
    /**
     * 0 - 99 系统预留
     *
     * Generated from protobuf enum <code>OK = 0;</code>
     */
    const OK = 0;
    /**
     * 错误的请求
     *
     * Generated from protobuf enum <code>Bad_Request = 1;</code>
     */
    const Bad_Request = 1;
    /**
     * 未授权
     *
     * Generated from protobuf enum <code>Unauthorized = 2;</code>
     */
    const Unauthorized = 2;
    /**
     * 内部服务器错误 
     *
     * Generated from protobuf enum <code>Internal_Server_Error = 3;</code>
     */
    const Internal_Server_Error = 3;
    /**
     * account 服务从100 - 199
     *
     * Generated from protobuf enum <code>EMAIL_EXISTED = 100;</code>
     */
    const EMAIL_EXISTED = 100;
    /**
     * 无效的session
     *
     * Generated from protobuf enum <code>SESSION_INVALID = 101;</code>
     */
    const SESSION_INVALID = 101;
    /**
     * 账户不存在
     *
     * Generated from protobuf enum <code>EMAIL_NOT_EXISTED = 102;</code>
     */
    const EMAIL_NOT_EXISTED = 102;
    /**
     * 密码错误
     *
     * Generated from protobuf enum <code>PASSWORD_ERROR = 103;</code>
     */
    const PASSWORD_ERROR = 103;
}

