<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protobuf.EmailRequest</code>
 */
class EmailRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     */
    private $user_id = '';
    /**
     * Generated from protobuf field <code>string Subject = 2;</code>
     */
    private $Subject = '';
    /**
     * Generated from protobuf field <code>string Body = 3;</code>
     */
    private $Body = '';

    public function __construct() {
        \GPBMetadata\Account::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Subject = 2;</code>
     * @return string
     */
    public function getSubject()
    {
        return $this->Subject;
    }

    /**
     * Generated from protobuf field <code>string Subject = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSubject($var)
    {
        GPBUtil::checkString($var, True);
        $this->Subject = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Body = 3;</code>
     * @return string
     */
    public function getBody()
    {
        return $this->Body;
    }

    /**
     * Generated from protobuf field <code>string Body = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, True);
        $this->Body = $var;

        return $this;
    }

}

