<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resume.proto

namespace Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protobuf.UpdateProfileResponse</code>
 */
class UpdateProfileResponse extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Resume::initOnce();
        parent::__construct();
    }

}

