<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: code.proto

namespace GPBMetadata;

class Code
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac0010a0a636f64652e70726f746f120870726f746f6275662a9f010a04" .
            "436f646512060a024f4b1000120f0a0b4261645f52657175657374100112" .
            "100a0c556e617574686f72697a6564100212190a15496e7465726e616c5f" .
            "5365727665725f4572726f72100312110a0d454d41494c5f455849535445" .
            "44106412130a0f53455353494f4e5f494e56414c4944106512150a11454d" .
            "41494c5f4e4f545f45584953544544106612120a0e50415353574f52445f" .
            "4552524f521067620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

